### ISSUE TITLE
MMOItems not working

### ISSUE THREAD

**Issue by Elioz** [brcdev-minecraft/shopgui-api#22]
Hi,

Tried to set MMOItem in shop, I get this error in console,

```
[00:17:13] [Server thread/WARN]: [ShopGUIPlus] Task #7912 for ShopGUIPlus v1.59.0 generated an exception
java.lang.NullPointerException: null
	at net.Indyuce.mmoitems.api.util.TemplateMap.getValue(TemplateMap.java:42) ~[?:?]
	at net.Indyuce.mmoitems.manager.TemplateManager.getTemplate(TemplateManager.java:46) ~[?:?]
	at net.Indyuce.mmoitems.MMOItems.getMMOItem(MMOItems.java:581) ~[?:?]
	at net.Indyuce.mmoitems.manager.ItemManager.getMMOItem(ItemManager.java:26) ~[?:?]
	at net.brcdev.shopgui.provider.item.MMOItemsItemProvider.loadItem(MMOItemsItemProvider.java:37) ~[?:?]
	at net.brcdev.shopgui.item.ItemManager.loadItem(ItemManager.java:70) ~[?:?]
	at net.brcdev.shopgui.util.ItemUtils.loadItemStackFromConfig(ItemUtils.java:93) ~[?:?]
	at net.brcdev.shopgui.shop.ShopManager.loadShopItems(ShopManager.java:249) ~[?:?]
	at net.brcdev.shopgui.shop.ShopManager.loadShop(ShopManager.java:183) ~[?:?]
	at net.brcdev.shopgui.shop.ShopManager.loadShops(ShopManager.java:109) ~[?:?]
	at net.brcdev.shopgui.shop.ShopManager.load(ShopManager.java:71) ~[?:?]
	at net.brcdev.shopgui.ShopGuiPlugin.loadAfterServerLoaded(ShopGuiPlugin.java:218) ~[?:?]
	at net.brcdev.shopgui.task.LoadShopsTask.run(LoadShopsTask.java:26) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-579]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-579]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Paper-579]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-579]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-579]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-579]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-579]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Thank you.

**Comment by brcdev** [comment]
This repository and issues are dedicated for API-related issues only. Please use our Discord and other means of communication for reporting bugs with the plugin itself.
