### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Rap3erka** [brcdev-minecraft/shopgui-api#24]
[15:12:30 ERROR]: Could not pass event InventoryClickEvent to ShopGUIPlus v1.62.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_272]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_272]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.isUnbreakable()Z
        at net.brcdev.shopgui.util.ItemUtils.compareItemStacks(ItemUtils.java:597) ~[?:?]
        at net.brcdev.shopgui.gui.gui.AmountSelectionGui.isSlotEmpty(AmountSelectionGui.java:255) ~[?:?]
        at net.brcdev.shopgui.gui.gui.AmountSelectionGui.handleAmountChange(AmountSelectionGui.java:149) ~[?:?]
        at net.brcdev.shopgui.gui.gui.AmountSelectionGui.createInventory(AmountSelectionGui.java:123) ~[?:?]
        at net.brcdev.shopgui.gui.gui.AmountSelectionGui.<init>(AmountSelectionGui.java:38) ~[?:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickBuyItem(PlayerListener.java:469) ~[?:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickShopGui(PlayerListener.java:227) ~[?:?]
        at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:148) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 16 more

**Comment by brcdev** [comment]
This repository and issues are dedicated for API-related issues only. Please use our Discord and other means of communication for reporting bugs with the plugin itself.
