### ISSUE TITLE
ShopGUIPlus v1.78.0 with SilkSpawners

### ISSUE THREAD

**Issue by Incluuu** [brcdev-minecraft/shopgui-api#31]
Purpur 1.19.2
client version: 1.12.2

ShopGUIPlusSilkSpawnersBridge-1.4.0
ShopGUIPlus v1.78.0

issues:
Could not pass event InventoryClickEvent to ShopGUIPlus v1.78.0
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because the return value of "java.lang.reflect.Method.invoke(Object, Object[])" is null
        at net.brcdev.shopgui.bridge.silkspawners.spawner.SilkSpawnersCurrentProvider.getSpawnerEntityType(SilkSpawnersCurrentProvider.java:49) ~[ShopGUIPlusSilkSpawnersBridge-1.4.0.jar:?]
        at net.brcdev.shopgui.spawner.SpawnerManager.getEntityType(SpawnerManager.java:47) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.util.ItemUtils.compareItemStacks(ItemUtils.java:618) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.util.InventoryUtils.canPlayerCarryItem(InventoryUtils.java:99) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.handleItemBuy(ShopManager.java:899) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:403) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:141) ~[ShopGUIPlus-1.78.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor602.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1778]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3400) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1388) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1365) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1778]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by brcdev** [comment]
This repository and issues are dedicated for API-related issues only. Please use our Discord and other means of communication for reporting bugs with the plugin itself.
